### ISSUE TITLE
Meta: blocking issues for beta deployment

### ISSUE THREAD

**Issue by bhutz** [oss-slu/dads#138]
The following items needs to be accomplished before a beta version is deployed

# Search Page

- [ ] Remove Class Filter
- [ ] Fix Field label filter
- [ ] Test Rational Periodic Points filter
- [ ] Implement Rational Preperiodic filter
- [ ] Remove Indeterminancy locus filter

# Detail Page
- [ ] Fix main functions details: correct data and correct fields
      - Standard model = the polynomials contained in the model specificed by display_model
      - field of definition = base_field_label ( should like to LMFDB)
      - automorphism group cardinality
      - min Field of definition = remove
      - field of moduli = remove
      - Divided into a second table containing
        - Is_PCF
        - Is Newton? = functions_dim_1_NF -> is_newton
        - Is Lattes? = functions_dim_1_NF -> is_lattes
        - Is Chebyshev? = functions_dim_1_NF -> is_chebshev
        - Is Polynomial? = functions_dim_1_NF -> is_polynomial

- [ ] Rational Preperiodic Points
      - This needs to be a table of values. The column values come from rational_prepeiodic_dim_1_NF joined with graphs_dim_1_nf.
        Specifically, find all the rows which contain function_id. The table will have one row per base_field_label with the data coming from graph_dim_1_nf with the graph_id in the rational_preperiodic_dim_1_NF table
    - Cardinality = cardinality
    - field label (rename this to "Field of Definitioin") = base_field_label (from the rational_preperidoic table)
    - cycle lengths = periodic_cycles
    - component sizes = preperiodic_components
    - Periodic Points Basis = rational_periodic_points (from rational_preperiodic table)
    - as directed graph = (need to compute from "edges" data)
    - adjacency matrix = (need to compute from "edges" data)

- [ ] Remove automorphism group block

- [ ] Critical Points
     - update data
     - Postcritically Finite? = function_dim_1_NF-> is_pcf
     - Cardinality = function_dim_1_NF -> cp-cardinality
     - Field of Definition = function_dim_1_NF -> cp-field_of_defn

- [ ] Critical Point Portrait
   - update data
   - only show when map is PCF
   - Cardinality = graphs_dim_1_NF -> cardinality (references from functions_dim_1_NF -> critical_portrait_graph_id)
   - size of Post Critical Set = graphs_dim_1_NF -> positive_in_degree
   - as directed graph = (need to compute from "edges" data from graphs_dim_1_NF)
   - adjacency matrix = (need to compute from "edges" data)
   - cycle lengths = graphs_dim_1_NF -> periodic_cycles
   - component sizes = graphs_dim_1_NF -> preperiodic_components
   - structure = remove

- [ ] Models
- Make it dynamic. Show only models that are relevant
- Fix Polynomials formatting. Surrounding () and fix trailing +
- add field of definition

- [ ] Add families information (dynamic table)
- family label (link to family details (when implemented)
- family name
- family model

- [ ] add rational twist information (dynamic table)
A rational twist is a related function
- label for each twist (link)
- standard model for each twist
